### ISSUE TITLE
关于创建非tg账户

### ISSUE THREAD

**Issue by pattonbina** [berry8838/Sakura_embyboss#22]
你好
前面版本还能创建非tg用户，但是今天发现非tg用户在创建时提示传入参数的错误

Embyservice.emby_create() takes 3 positional arguments but 6 were given
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/app/bot/modules/extra/create.py", line 38, in login_account
    pwd1 = await emby.emby_create(5210, name, 1234, days, 'o')
TypeError: Embyservice.emby_create() takes 3 positional arguments but 6 were given

请问这个功能是准备完全不做了么，之前问过您，你说准备清理掉数据库中的emby2，如果不准备做了，可以我希望我能定制一下这个功能，非常感谢

**Comment by pattonbina** [comment]
另外，我填写的群组id，虽然一直正常运行，但是后台会报错
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 242, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/sync.py", line 78, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, main_loop).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/pyromod/listen/message_handler.py", line 98, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/app/bot/modules/commands/start.py", line 48, in p_start
    if not await user_in_group_filter(_, msg):
  File "/app/bot/func_helper/filters.py", line 52, in user_in_group_filter
    u = await client.get_chat_member(chat_id=int(i), user_id=uid)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/chats/get_chat_member.py", line 55, in get_chat_member
    chat = await self.resolve_peer(chat_id)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 89, in resolve_peer
    peer_type = utils.get_peer_type(peer_id)
  File "/usr/local/lib/python3.10/site-packages/pyrogram/utils.py", line 246, in get_peer_type
    raise ValueError(f"Peer id invalid: {peer_id}")
ValueError: Peer id invalid: -xxxxxxx(原日志为群组id)

**Comment by berry8838** [comment]
关于非tg账户因为之前改进了创建过程，后续合适会加回来的，命令设置已经收到很多反馈，接下来会处理的，嗯

**Comment by berry8838** [comment]
done_
随便搓了一下，有问题请反馈，没有请关闭
